version: '3.8'
services:

  nodeapp: 
    container_name: appnode
    ports:
    - "3000:3000"
    build: .
    networks:
    - app-network
    depends_on:
      - mongo
    links:
      - mongo

  mongodb:
    container_name: mongodb
    image: mongo
    networks:
    - app-network
    ports:
      - 27017:27017
    restart: always

networks:
  app-network:


