version: '3.8'
services:

  node: 
    container_name: appnode
    ports:
    - "3000:3000"
    build: .
    networks:
    - app-network
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    container_name: mongodb
    image: mongo:latest
    networks:
    - app-network
    restart: always

networks:
  app-network:


